/*
 * Teragrep DPL Spark Integration PTH-07
 * Copyright (C) 2022  Suomen Kanuuna Oy
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://github.com/teragrep/teragrep/blob/main/LICENSE>.
 *
 *
 * Additional permission under GNU Affero General Public License version 3
 * section 7
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with other code, such other code is not for that reason alone subject to any
 * of the requirements of the GNU Affero GPL version 3 as long as this Program
 * is the same Program as licensed from Suomen Kanuuna Oy without any additional
 * modifications.
 *
 * Supplemented terms under GNU Affero General Public License version 3
 * section 7
 *
 * Origin of the software must be attributed to Suomen Kanuuna Oy. Any modified
 * versions must be marked as "Modified version of" The Program.
 *
 * Names of the licensors and authors may not be used for publicity purposes.
 *
 * No rights are granted for use of trade names, trademarks, or service marks
 * which are in The Program if any.
 *
 * Licensee must indemnify licensors and authors for any liability that these
 * contractual assumptions impose on licensors and authors.
 *
 * To the extent this program is licensed as part of the Commercial versions of
 * Teragrep, the applicable Commercial License may apply to this file if you as
 * a licensee so wish it.
 */
package com.teragrep.pth_07.ui.elements.table_dynamic.formats;

import com.teragrep.zep_01.interpreter.InterpreterException;
import com.teragrep.zep_01.interpreter.InterpreterResult;
import com.teragrep.zep_01.interpreter.thrift.DataTablesOptions;
import com.teragrep.zep_01.interpreter.thrift.DataTablesSearch;
import com.teragrep.zep_01.interpreter.thrift.Options;
import jakarta.json.*;
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.types.StructField;
import org.apache.spark.sql.types.StructType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.StringReader;
import java.util.ArrayList;

public class DataTablesFormat implements DatasetFormat{
    private static final Logger LOGGER = LoggerFactory.getLogger(DataTablesFormat.class);
    private StructType previousSchema;
    private int draw;

    public DataTablesFormat(){
        this.previousSchema = new StructType();
    }

    public JsonObject format(Dataset<Row> dataset) throws InterpreterException{
        DataTablesOptions defaultDtOptions = new DataTablesOptions(0,0,50,new DataTablesSearch("",false,new ArrayList<>()),new ArrayList<>(), new ArrayList<>());
        Options defaultOptions = Options.dataTablesOptions(defaultDtOptions);
        return format(dataset, defaultOptions);
    }
    public JsonObject format(Dataset<Row> dataset, Options options) throws InterpreterException{
        // Generated implementations of Thrift unions don't implement interfaces, so we have to use the autogenerated functions to get the proper type of object from Options.
        if(!options.isSetDataTablesOptions()){
            throw new InterpreterException("Unsupported options type!");
        }
        DataTablesOptions dtOptions = options.getDataTablesOptions();
        if(dataset == null){
            throw new InterpreterException("Attempting to draw an empty dataset!");
        }

        StructType schema = dataset.schema();

        // reset draw when schema changes
        if(!schema.equals(previousSchema)){
            draw = 1;
        }
        // ncrement draw when schema has not changed.
        else {
            draw++;
        }
        previousSchema = schema;

        // headers
        JsonArrayBuilder headersBuilder = Json.createArrayBuilder();
        for (StructField header:dataset.schema().fields()) {
            headersBuilder.add(header.name());
        }
        JsonArray headers = headersBuilder.build();

        // search
        final Dataset<Row> searched;
        if(!dtOptions.getSearch().getValue().isEmpty()){
            searched = dataset.filter(org.apache.spark.sql.functions.col("_raw"));
        }
        else {
            searched = dataset;
        }

        // paginate
        final Dataset<Row> paginated;
        paginated = searched.offset(dtOptions.getStart()).limit(dtOptions.getLength());

        // json
        JsonArrayBuilder dataBuilder = Json.createArrayBuilder();
        for (String jsonRow:paginated.toJSON().collectAsList()) {
            dataBuilder.add(Json.createReader(new StringReader(jsonRow)).readObject());
        }
        JsonArray data = dataBuilder.build();
        long recordsTotal = dataset.count();
        long recordsFiltered = searched.count();
        boolean isAggregated = isAggregated(dataset.schema());

        JsonObject json = Json.createObjectBuilder()
                .add("data",Json.createObjectBuilder()
                        .add("headers",headers)
                        .add("data", data)
                        .add("draw", draw)
                        .add("recordsTotal", recordsTotal)
                        .add("recordsFiltered", recordsFiltered)
                        .build())
                .add("isAggregated",isAggregated)
                .add("type",InterpreterResult.Type.DATATABLES.label)
                .build();
        return json;
    }
    private boolean isAggregated(StructType schema) {
        for (StructField field:schema.fields()) {
            if(field.metadata().contains("dpl_internal_isGroupByColumn")){
                return true;
            }
        }
        return false;
    }

    @Override
    public String type(){
        return InterpreterResult.Type.DATATABLES.label;
    }
}
