/*
 * Teragrep DPL Spark Integration PTH-07
 * Copyright (C) 2022  Suomen Kanuuna Oy
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://github.com/teragrep/teragrep/blob/main/LICENSE>.
 *
 *
 * Additional permission under GNU Affero General Public License version 3
 * section 7
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with other code, such other code is not for that reason alone subject to any
 * of the requirements of the GNU Affero GPL version 3 as long as this Program
 * is the same Program as licensed from Suomen Kanuuna Oy without any additional
 * modifications.
 *
 * Supplemented terms under GNU Affero General Public License version 3
 * section 7
 *
 * Origin of the software must be attributed to Suomen Kanuuna Oy. Any modified
 * versions must be marked as "Modified version of" The Program.
 *
 * Names of the licensors and authors may not be used for publicity purposes.
 *
 * No rights are granted for use of trade names, trademarks, or service marks
 * which are in The Program if any.
 *
 * Licensee must indemnify licensors and authors for any liability that these
 * contractual assumptions impose on licensors and authors.
 *
 * To the extent this program is licensed as part of the Commercial versions of
 * Teragrep, the applicable Commercial License may apply to this file if you as
 * a licensee so wish it.
 */
package com.teragrep.pth_07.ui.elements.table_dynamic.formats;

import com.teragrep.zep_01.interpreter.InterpreterException;
import com.teragrep.zep_01.interpreter.InterpreterResult;
import com.teragrep.zep_01.interpreter.thrift.DataTablesOptions;
import com.teragrep.zep_01.interpreter.thrift.Options;
import jakarta.json.*;
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;
import org.apache.spark.sql.types.StructField;
import org.apache.spark.sql.types.StructType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.StringReader;
import java.util.ArrayList;
import java.util.List;

/**
 * Formats a given Dataset to expected format for DataTables visualization library.
 * Keeps an internal "draw" counter, which increments by 1 every time a new formatting request is received using the same Schema.
 * "draw" counter resets when a Dataset with a new Schema is encountered.
 * Keeps the rows of a Dataset in a cache to avoid unnecessary calls to Dataset.collectAsList() when performing for example pagination requests.
 * Cache is updated when a new Dataset is received
 */
public class DataTablesFormat implements DatasetFormat{
    private static final Logger LOGGER = LoggerFactory.getLogger(DataTablesFormat.class);
    private Dataset<Row> currentDataset;
    private List<String> cachedRows = new ArrayList<>();
    private int draw;

    public DataTablesFormat(){
    }
    /**
     * Format a given Dataset into DataTables format using the parameters in the given Options object
     * Will use cached data if given Dataset is equal to the previous Dataset.
     * @param dataset Dataset to format
     * @param options Thrift union object that must contain a DataTablesOptions object.
     * @return JsonObject formatted to style expected by DataTables visualization library.
     * @throws InterpreterException Thrown when Dataset or Options given are invalid.
     */
    public JsonObject format(Dataset<Row> dataset, Options options) throws InterpreterException{
        // Generated implementations of Thrift unions don't implement interfaces, so we have to use the autogenerated functions to get the proper type of object from Options.
        if(!options.isSetDataTablesOptions()){
            throw new InterpreterException("Unsupported options type!");
        }
        DataTablesOptions dtOptions = options.getDataTablesOptions();
        if(dataset == null){
            throw new InterpreterException("Attempting to draw an empty dataset!");
        }

        if(currentDataset == null){
            draw = 1;
            cachedRows = dataset.toJSON().collectAsList();
        }
        else {
            if(currentDataset.schema().equals(dataset.schema())){
                draw++;
            }
            else {
                draw = 1;
            }
            // If the provided dataset has different data as previously formatted dataset, update the cached rows.
            // If data is the same, we can avoid an unnecessary call to collectAsList()
            if(!currentDataset.equals(dataset)){
                cachedRows = dataset.toJSON().collectAsList();
            }
        }
        currentDataset = dataset;

        // headers
        JsonArrayBuilder headersBuilder = Json.createArrayBuilder();
        for (StructField header:currentDataset.schema().fields()) {
            headersBuilder.add(header.name());
        }
        JsonArray headers = headersBuilder.build();

        // search
        List<String> searchedRows = search(cachedRows, dtOptions.getSearch().getValue());

        // paginate
        List<String> paginatedRows = paginate(searchedRows, dtOptions.getStart(), dtOptions.getLength());

        // json
        JsonArrayBuilder dataBuilder = Json.createArrayBuilder();
        for (String jsonRow:paginatedRows) {
            dataBuilder.add(Json.createReader(new StringReader(jsonRow)).readObject());
        }
        JsonArray data = dataBuilder.build();
        long recordsTotal = cachedRows.size();
        long recordsFiltered = searchedRows.size();
        boolean isAggregated = isAggregated(currentDataset.schema());

        JsonObject json = Json.createObjectBuilder()
                .add("data",Json.createObjectBuilder()
                        .add("data", data)
                        .add("draw", draw)
                        .add("recordsTotal", recordsTotal)
                        .add("recordsFiltered", recordsFiltered)
                        .build())
                .add("options",Json.createObjectBuilder()
                        .add("headers",headers)
                        .build())
                .add("isAggregated",isAggregated)
                .add("type",InterpreterResult.Type.DATATABLES.label)
                .build();
        return json;
    }
    private boolean isAggregated(StructType schema) {
        for (StructField field:schema.fields()) {
            if(field.metadata().contains("dpl_internal_isGroupByColumn")){
                return true;
            }
        }
        return false;
    }

    @Override
    public String type(){
        return InterpreterResult.Type.DATATABLES.label;
    }

    private List<String> search(List<String> rows, String searchString){
        List<String> searchedRows = new ArrayList<>();
        if (!"".equals(searchString)) {
            try {
                for (String row : rows) {
                    JsonReader reader = Json.createReader(new StringReader(row));
                    JsonObject line = reader.readObject();

                    // NOTE hard coded to _raw column
                    JsonString _raw = line.getJsonString("_raw");
                    if (_raw != null) {
                        String _rawString = _raw.getString();
                        if (_rawString != null) {
                            if (_rawString.contains(searchString)) {
                                // _raw matches, add whole row to result set
                                searchedRows.add(row);
                            }
                        }
                    }
                    reader.close();
                }
            } catch (JsonException | IllegalStateException e) {
                LOGGER.error(e.toString());
            }
        }
        else {
            searchedRows = rows;
        }
        return searchedRows;
    }

    private List<String> paginate(List<String> rows, int pageStart, int pageSize){
        // ranges must be greater than 0
        int fromIndex = Math.max(pageStart, 0);
        int toIndex = Math.max(fromIndex + pageSize, 0);

        // list must end at the maximum size
        if (toIndex > rows.size()) {
            toIndex = rows.size();
        }

        // list range must be positive
        if (fromIndex > toIndex) {
            fromIndex = toIndex;
        }

        List<String> paginatedRows = rows.subList(fromIndex, toIndex);
        return paginatedRows;
    }
}
