/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.teragrep.zep_01.interpreter.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.20.0)", date = "2026-02-19")
public class DataTablesSearch implements org.apache.thrift.TBase<DataTablesSearch, DataTablesSearch._Fields>, java.io.Serializable, Cloneable, Comparable<DataTablesSearch> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DataTablesSearch");

  private static final org.apache.thrift.protocol.TField VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("value", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField REGEX_FIELD_DESC = new org.apache.thrift.protocol.TField("regex", org.apache.thrift.protocol.TType.BOOL, (short)2);
  private static final org.apache.thrift.protocol.TField FIXED_FIELD_DESC = new org.apache.thrift.protocol.TField("fixed", org.apache.thrift.protocol.TType.LIST, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new DataTablesSearchStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new DataTablesSearchTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String value; // required
  public boolean regex; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> fixed; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    VALUE((short)1, "value"),
    REGEX((short)2, "regex"),
    FIXED((short)3, "fixed");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // VALUE
          return VALUE;
        case 2: // REGEX
          return REGEX;
        case 3: // FIXED
          return FIXED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __REGEX_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.VALUE, new org.apache.thrift.meta_data.FieldMetaData("value", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.REGEX, new org.apache.thrift.meta_data.FieldMetaData("regex", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.FIXED, new org.apache.thrift.meta_data.FieldMetaData("fixed", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DataTablesSearch.class, metaDataMap);
  }

  public DataTablesSearch() {
  }

  public DataTablesSearch(
    java.lang.String value,
    boolean regex,
    java.util.List<java.lang.String> fixed)
  {
    this();
    this.value = value;
    this.regex = regex;
    setRegexIsSet(true);
    this.fixed = fixed;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DataTablesSearch(DataTablesSearch other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetValue()) {
      this.value = other.value;
    }
    this.regex = other.regex;
    if (other.isSetFixed()) {
      java.util.List<java.lang.String> __this__fixed = new java.util.ArrayList<java.lang.String>(other.fixed);
      this.fixed = __this__fixed;
    }
  }

  @Override
  public DataTablesSearch deepCopy() {
    return new DataTablesSearch(this);
  }

  @Override
  public void clear() {
    this.value = null;
    setRegexIsSet(false);
    this.regex = false;
    this.fixed = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getValue() {
    return this.value;
  }

  public DataTablesSearch setValue(@org.apache.thrift.annotation.Nullable java.lang.String value) {
    this.value = value;
    return this;
  }

  public void unsetValue() {
    this.value = null;
  }

  /** Returns true if field value is set (has been assigned a value) and false otherwise */
  public boolean isSetValue() {
    return this.value != null;
  }

  public void setValueIsSet(boolean value) {
    if (!value) {
      this.value = null;
    }
  }

  public boolean isRegex() {
    return this.regex;
  }

  public DataTablesSearch setRegex(boolean regex) {
    this.regex = regex;
    setRegexIsSet(true);
    return this;
  }

  public void unsetRegex() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __REGEX_ISSET_ID);
  }

  /** Returns true if field regex is set (has been assigned a value) and false otherwise */
  public boolean isSetRegex() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __REGEX_ISSET_ID);
  }

  public void setRegexIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __REGEX_ISSET_ID, value);
  }

  public int getFixedSize() {
    return (this.fixed == null) ? 0 : this.fixed.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getFixedIterator() {
    return (this.fixed == null) ? null : this.fixed.iterator();
  }

  public void addToFixed(java.lang.String elem) {
    if (this.fixed == null) {
      this.fixed = new java.util.ArrayList<java.lang.String>();
    }
    this.fixed.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getFixed() {
    return this.fixed;
  }

  public DataTablesSearch setFixed(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> fixed) {
    this.fixed = fixed;
    return this;
  }

  public void unsetFixed() {
    this.fixed = null;
  }

  /** Returns true if field fixed is set (has been assigned a value) and false otherwise */
  public boolean isSetFixed() {
    return this.fixed != null;
  }

  public void setFixedIsSet(boolean value) {
    if (!value) {
      this.fixed = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case VALUE:
      if (value == null) {
        unsetValue();
      } else {
        setValue((java.lang.String)value);
      }
      break;

    case REGEX:
      if (value == null) {
        unsetRegex();
      } else {
        setRegex((java.lang.Boolean)value);
      }
      break;

    case FIXED:
      if (value == null) {
        unsetFixed();
      } else {
        setFixed((java.util.List<java.lang.String>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case VALUE:
      return getValue();

    case REGEX:
      return isRegex();

    case FIXED:
      return getFixed();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case VALUE:
      return isSetValue();
    case REGEX:
      return isSetRegex();
    case FIXED:
      return isSetFixed();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof DataTablesSearch)
      return this.equals((DataTablesSearch)that);
    return false;
  }

  public boolean equals(DataTablesSearch that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_value = true && this.isSetValue();
    boolean that_present_value = true && that.isSetValue();
    if (this_present_value || that_present_value) {
      if (!(this_present_value && that_present_value))
        return false;
      if (!this.value.equals(that.value))
        return false;
    }

    boolean this_present_regex = true;
    boolean that_present_regex = true;
    if (this_present_regex || that_present_regex) {
      if (!(this_present_regex && that_present_regex))
        return false;
      if (this.regex != that.regex)
        return false;
    }

    boolean this_present_fixed = true && this.isSetFixed();
    boolean that_present_fixed = true && that.isSetFixed();
    if (this_present_fixed || that_present_fixed) {
      if (!(this_present_fixed && that_present_fixed))
        return false;
      if (!this.fixed.equals(that.fixed))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetValue()) ? 131071 : 524287);
    if (isSetValue())
      hashCode = hashCode * 8191 + value.hashCode();

    hashCode = hashCode * 8191 + ((regex) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetFixed()) ? 131071 : 524287);
    if (isSetFixed())
      hashCode = hashCode * 8191 + fixed.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(DataTablesSearch other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetValue(), other.isSetValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.value, other.value);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRegex(), other.isSetRegex());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRegex()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.regex, other.regex);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetFixed(), other.isSetFixed());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFixed()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fixed, other.fixed);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("DataTablesSearch(");
    boolean first = true;

    sb.append("value:");
    if (this.value == null) {
      sb.append("null");
    } else {
      sb.append(this.value);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("regex:");
    sb.append(this.regex);
    first = false;
    if (!first) sb.append(", ");
    sb.append("fixed:");
    if (this.fixed == null) {
      sb.append("null");
    } else {
      sb.append(this.fixed);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DataTablesSearchStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DataTablesSearchStandardScheme getScheme() {
      return new DataTablesSearchStandardScheme();
    }
  }

  private static class DataTablesSearchStandardScheme extends org.apache.thrift.scheme.StandardScheme<DataTablesSearch> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, DataTablesSearch struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.value = iprot.readString();
              struct.setValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // REGEX
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.regex = iprot.readBool();
              struct.setRegexIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // FIXED
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list18 = iprot.readListBegin();
                struct.fixed = new java.util.ArrayList<java.lang.String>(_list18.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem19;
                for (int _i20 = 0; _i20 < _list18.size; ++_i20)
                {
                  _elem19 = iprot.readString();
                  struct.fixed.add(_elem19);
                }
                iprot.readListEnd();
              }
              struct.setFixedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, DataTablesSearch struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.value != null) {
        oprot.writeFieldBegin(VALUE_FIELD_DESC);
        oprot.writeString(struct.value);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(REGEX_FIELD_DESC);
      oprot.writeBool(struct.regex);
      oprot.writeFieldEnd();
      if (struct.fixed != null) {
        oprot.writeFieldBegin(FIXED_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.fixed.size()));
          for (java.lang.String _iter21 : struct.fixed)
          {
            oprot.writeString(_iter21);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DataTablesSearchTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DataTablesSearchTupleScheme getScheme() {
      return new DataTablesSearchTupleScheme();
    }
  }

  private static class DataTablesSearchTupleScheme extends org.apache.thrift.scheme.TupleScheme<DataTablesSearch> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DataTablesSearch struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetValue()) {
        optionals.set(0);
      }
      if (struct.isSetRegex()) {
        optionals.set(1);
      }
      if (struct.isSetFixed()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetValue()) {
        oprot.writeString(struct.value);
      }
      if (struct.isSetRegex()) {
        oprot.writeBool(struct.regex);
      }
      if (struct.isSetFixed()) {
        {
          oprot.writeI32(struct.fixed.size());
          for (java.lang.String _iter22 : struct.fixed)
          {
            oprot.writeString(_iter22);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DataTablesSearch struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.value = iprot.readString();
        struct.setValueIsSet(true);
      }
      if (incoming.get(1)) {
        struct.regex = iprot.readBool();
        struct.setRegexIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list23 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
          struct.fixed = new java.util.ArrayList<java.lang.String>(_list23.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _elem24;
          for (int _i25 = 0; _i25 < _list23.size; ++_i25)
          {
            _elem24 = iprot.readString();
            struct.fixed.add(_elem24);
          }
        }
        struct.setFixedIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

