/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.teragrep.zep_01.interpreter.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.20.0)", date = "2026-02-19")
public class DataTablesColumns implements org.apache.thrift.TBase<DataTablesColumns, DataTablesColumns._Fields>, java.io.Serializable, Cloneable, Comparable<DataTablesColumns> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DataTablesColumns");

  private static final org.apache.thrift.protocol.TField DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("data", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField ORDERABLE_FIELD_DESC = new org.apache.thrift.protocol.TField("orderable", org.apache.thrift.protocol.TType.BOOL, (short)3);
  private static final org.apache.thrift.protocol.TField SEARCH_FIELD_DESC = new org.apache.thrift.protocol.TField("search", org.apache.thrift.protocol.TType.STRUCT, (short)4);
  private static final org.apache.thrift.protocol.TField SEARCHABLE_FIELD_DESC = new org.apache.thrift.protocol.TField("searchable", org.apache.thrift.protocol.TType.BOOL, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new DataTablesColumnsStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new DataTablesColumnsTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String data; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String name; // required
  public boolean orderable; // required
  public @org.apache.thrift.annotation.Nullable DataTablesSearch search; // required
  public boolean searchable; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DATA((short)1, "data"),
    NAME((short)2, "name"),
    ORDERABLE((short)3, "orderable"),
    SEARCH((short)4, "search"),
    SEARCHABLE((short)5, "searchable");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DATA
          return DATA;
        case 2: // NAME
          return NAME;
        case 3: // ORDERABLE
          return ORDERABLE;
        case 4: // SEARCH
          return SEARCH;
        case 5: // SEARCHABLE
          return SEARCHABLE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ORDERABLE_ISSET_ID = 0;
  private static final int __SEARCHABLE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DATA, new org.apache.thrift.meta_data.FieldMetaData("data", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ORDERABLE, new org.apache.thrift.meta_data.FieldMetaData("orderable", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.SEARCH, new org.apache.thrift.meta_data.FieldMetaData("search", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, DataTablesSearch.class)));
    tmpMap.put(_Fields.SEARCHABLE, new org.apache.thrift.meta_data.FieldMetaData("searchable", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DataTablesColumns.class, metaDataMap);
  }

  public DataTablesColumns() {
  }

  public DataTablesColumns(
    java.lang.String data,
    java.lang.String name,
    boolean orderable,
    DataTablesSearch search,
    boolean searchable)
  {
    this();
    this.data = data;
    this.name = name;
    this.orderable = orderable;
    setOrderableIsSet(true);
    this.search = search;
    this.searchable = searchable;
    setSearchableIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DataTablesColumns(DataTablesColumns other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetData()) {
      this.data = other.data;
    }
    if (other.isSetName()) {
      this.name = other.name;
    }
    this.orderable = other.orderable;
    if (other.isSetSearch()) {
      this.search = new DataTablesSearch(other.search);
    }
    this.searchable = other.searchable;
  }

  @Override
  public DataTablesColumns deepCopy() {
    return new DataTablesColumns(this);
  }

  @Override
  public void clear() {
    this.data = null;
    this.name = null;
    setOrderableIsSet(false);
    this.orderable = false;
    this.search = null;
    setSearchableIsSet(false);
    this.searchable = false;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getData() {
    return this.data;
  }

  public DataTablesColumns setData(@org.apache.thrift.annotation.Nullable java.lang.String data) {
    this.data = data;
    return this;
  }

  public void unsetData() {
    this.data = null;
  }

  /** Returns true if field data is set (has been assigned a value) and false otherwise */
  public boolean isSetData() {
    return this.data != null;
  }

  public void setDataIsSet(boolean value) {
    if (!value) {
      this.data = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getName() {
    return this.name;
  }

  public DataTablesColumns setName(@org.apache.thrift.annotation.Nullable java.lang.String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public boolean isOrderable() {
    return this.orderable;
  }

  public DataTablesColumns setOrderable(boolean orderable) {
    this.orderable = orderable;
    setOrderableIsSet(true);
    return this;
  }

  public void unsetOrderable() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ORDERABLE_ISSET_ID);
  }

  /** Returns true if field orderable is set (has been assigned a value) and false otherwise */
  public boolean isSetOrderable() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ORDERABLE_ISSET_ID);
  }

  public void setOrderableIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ORDERABLE_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public DataTablesSearch getSearch() {
    return this.search;
  }

  public DataTablesColumns setSearch(@org.apache.thrift.annotation.Nullable DataTablesSearch search) {
    this.search = search;
    return this;
  }

  public void unsetSearch() {
    this.search = null;
  }

  /** Returns true if field search is set (has been assigned a value) and false otherwise */
  public boolean isSetSearch() {
    return this.search != null;
  }

  public void setSearchIsSet(boolean value) {
    if (!value) {
      this.search = null;
    }
  }

  public boolean isSearchable() {
    return this.searchable;
  }

  public DataTablesColumns setSearchable(boolean searchable) {
    this.searchable = searchable;
    setSearchableIsSet(true);
    return this;
  }

  public void unsetSearchable() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SEARCHABLE_ISSET_ID);
  }

  /** Returns true if field searchable is set (has been assigned a value) and false otherwise */
  public boolean isSetSearchable() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SEARCHABLE_ISSET_ID);
  }

  public void setSearchableIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SEARCHABLE_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case DATA:
      if (value == null) {
        unsetData();
      } else {
        setData((java.lang.String)value);
      }
      break;

    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((java.lang.String)value);
      }
      break;

    case ORDERABLE:
      if (value == null) {
        unsetOrderable();
      } else {
        setOrderable((java.lang.Boolean)value);
      }
      break;

    case SEARCH:
      if (value == null) {
        unsetSearch();
      } else {
        setSearch((DataTablesSearch)value);
      }
      break;

    case SEARCHABLE:
      if (value == null) {
        unsetSearchable();
      } else {
        setSearchable((java.lang.Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DATA:
      return getData();

    case NAME:
      return getName();

    case ORDERABLE:
      return isOrderable();

    case SEARCH:
      return getSearch();

    case SEARCHABLE:
      return isSearchable();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DATA:
      return isSetData();
    case NAME:
      return isSetName();
    case ORDERABLE:
      return isSetOrderable();
    case SEARCH:
      return isSetSearch();
    case SEARCHABLE:
      return isSetSearchable();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof DataTablesColumns)
      return this.equals((DataTablesColumns)that);
    return false;
  }

  public boolean equals(DataTablesColumns that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_data = true && this.isSetData();
    boolean that_present_data = true && that.isSetData();
    if (this_present_data || that_present_data) {
      if (!(this_present_data && that_present_data))
        return false;
      if (!this.data.equals(that.data))
        return false;
    }

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_orderable = true;
    boolean that_present_orderable = true;
    if (this_present_orderable || that_present_orderable) {
      if (!(this_present_orderable && that_present_orderable))
        return false;
      if (this.orderable != that.orderable)
        return false;
    }

    boolean this_present_search = true && this.isSetSearch();
    boolean that_present_search = true && that.isSetSearch();
    if (this_present_search || that_present_search) {
      if (!(this_present_search && that_present_search))
        return false;
      if (!this.search.equals(that.search))
        return false;
    }

    boolean this_present_searchable = true;
    boolean that_present_searchable = true;
    if (this_present_searchable || that_present_searchable) {
      if (!(this_present_searchable && that_present_searchable))
        return false;
      if (this.searchable != that.searchable)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetData()) ? 131071 : 524287);
    if (isSetData())
      hashCode = hashCode * 8191 + data.hashCode();

    hashCode = hashCode * 8191 + ((isSetName()) ? 131071 : 524287);
    if (isSetName())
      hashCode = hashCode * 8191 + name.hashCode();

    hashCode = hashCode * 8191 + ((orderable) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetSearch()) ? 131071 : 524287);
    if (isSetSearch())
      hashCode = hashCode * 8191 + search.hashCode();

    hashCode = hashCode * 8191 + ((searchable) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(DataTablesColumns other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetData(), other.isSetData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.data, other.data);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetName(), other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOrderable(), other.isSetOrderable());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOrderable()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.orderable, other.orderable);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSearch(), other.isSetSearch());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSearch()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.search, other.search);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSearchable(), other.isSetSearchable());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSearchable()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.searchable, other.searchable);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("DataTablesColumns(");
    boolean first = true;

    sb.append("data:");
    if (this.data == null) {
      sb.append("null");
    } else {
      sb.append(this.data);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("orderable:");
    sb.append(this.orderable);
    first = false;
    if (!first) sb.append(", ");
    sb.append("search:");
    if (this.search == null) {
      sb.append("null");
    } else {
      sb.append(this.search);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("searchable:");
    sb.append(this.searchable);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (search != null) {
      search.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DataTablesColumnsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DataTablesColumnsStandardScheme getScheme() {
      return new DataTablesColumnsStandardScheme();
    }
  }

  private static class DataTablesColumnsStandardScheme extends org.apache.thrift.scheme.StandardScheme<DataTablesColumns> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, DataTablesColumns struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.data = iprot.readString();
              struct.setDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ORDERABLE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.orderable = iprot.readBool();
              struct.setOrderableIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SEARCH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.search = new DataTablesSearch();
              struct.search.read(iprot);
              struct.setSearchIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // SEARCHABLE
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.searchable = iprot.readBool();
              struct.setSearchableIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, DataTablesColumns struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.data != null) {
        oprot.writeFieldBegin(DATA_FIELD_DESC);
        oprot.writeString(struct.data);
        oprot.writeFieldEnd();
      }
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ORDERABLE_FIELD_DESC);
      oprot.writeBool(struct.orderable);
      oprot.writeFieldEnd();
      if (struct.search != null) {
        oprot.writeFieldBegin(SEARCH_FIELD_DESC);
        struct.search.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SEARCHABLE_FIELD_DESC);
      oprot.writeBool(struct.searchable);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DataTablesColumnsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DataTablesColumnsTupleScheme getScheme() {
      return new DataTablesColumnsTupleScheme();
    }
  }

  private static class DataTablesColumnsTupleScheme extends org.apache.thrift.scheme.TupleScheme<DataTablesColumns> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DataTablesColumns struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetData()) {
        optionals.set(0);
      }
      if (struct.isSetName()) {
        optionals.set(1);
      }
      if (struct.isSetOrderable()) {
        optionals.set(2);
      }
      if (struct.isSetSearch()) {
        optionals.set(3);
      }
      if (struct.isSetSearchable()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetData()) {
        oprot.writeString(struct.data);
      }
      if (struct.isSetName()) {
        oprot.writeString(struct.name);
      }
      if (struct.isSetOrderable()) {
        oprot.writeBool(struct.orderable);
      }
      if (struct.isSetSearch()) {
        struct.search.write(oprot);
      }
      if (struct.isSetSearchable()) {
        oprot.writeBool(struct.searchable);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DataTablesColumns struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.data = iprot.readString();
        struct.setDataIsSet(true);
      }
      if (incoming.get(1)) {
        struct.name = iprot.readString();
        struct.setNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.orderable = iprot.readBool();
        struct.setOrderableIsSet(true);
      }
      if (incoming.get(3)) {
        struct.search = new DataTablesSearch();
        struct.search.read(iprot);
        struct.setSearchIsSet(true);
      }
      if (incoming.get(4)) {
        struct.searchable = iprot.readBool();
        struct.setSearchableIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

