/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Autogenerated by Thrift Compiler (0.20.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.teragrep.zep_01.interpreter.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.20.0)", date = "2026-02-19")
public class UPlotOptions implements org.apache.thrift.TBase<UPlotOptions, UPlotOptions._Fields>, java.io.Serializable, Cloneable, Comparable<UPlotOptions> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UPlotOptions");

  private static final org.apache.thrift.protocol.TField GRAPH_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("graphType", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new UPlotOptionsStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new UPlotOptionsTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String graphType; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    GRAPH_TYPE((short)1, "graphType");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // GRAPH_TYPE
          return GRAPH_TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.GRAPH_TYPE, new org.apache.thrift.meta_data.FieldMetaData("graphType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UPlotOptions.class, metaDataMap);
  }

  public UPlotOptions() {
  }

  public UPlotOptions(
    java.lang.String graphType)
  {
    this();
    this.graphType = graphType;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UPlotOptions(UPlotOptions other) {
    if (other.isSetGraphType()) {
      this.graphType = other.graphType;
    }
  }

  @Override
  public UPlotOptions deepCopy() {
    return new UPlotOptions(this);
  }

  @Override
  public void clear() {
    this.graphType = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getGraphType() {
    return this.graphType;
  }

  public UPlotOptions setGraphType(@org.apache.thrift.annotation.Nullable java.lang.String graphType) {
    this.graphType = graphType;
    return this;
  }

  public void unsetGraphType() {
    this.graphType = null;
  }

  /** Returns true if field graphType is set (has been assigned a value) and false otherwise */
  public boolean isSetGraphType() {
    return this.graphType != null;
  }

  public void setGraphTypeIsSet(boolean value) {
    if (!value) {
      this.graphType = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case GRAPH_TYPE:
      if (value == null) {
        unsetGraphType();
      } else {
        setGraphType((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case GRAPH_TYPE:
      return getGraphType();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case GRAPH_TYPE:
      return isSetGraphType();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof UPlotOptions)
      return this.equals((UPlotOptions)that);
    return false;
  }

  public boolean equals(UPlotOptions that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_graphType = true && this.isSetGraphType();
    boolean that_present_graphType = true && that.isSetGraphType();
    if (this_present_graphType || that_present_graphType) {
      if (!(this_present_graphType && that_present_graphType))
        return false;
      if (!this.graphType.equals(that.graphType))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetGraphType()) ? 131071 : 524287);
    if (isSetGraphType())
      hashCode = hashCode * 8191 + graphType.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(UPlotOptions other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetGraphType(), other.isSetGraphType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGraphType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.graphType, other.graphType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("UPlotOptions(");
    boolean first = true;

    sb.append("graphType:");
    if (this.graphType == null) {
      sb.append("null");
    } else {
      sb.append(this.graphType);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UPlotOptionsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public UPlotOptionsStandardScheme getScheme() {
      return new UPlotOptionsStandardScheme();
    }
  }

  private static class UPlotOptionsStandardScheme extends org.apache.thrift.scheme.StandardScheme<UPlotOptions> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, UPlotOptions struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // GRAPH_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.graphType = iprot.readString();
              struct.setGraphTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, UPlotOptions struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.graphType != null) {
        oprot.writeFieldBegin(GRAPH_TYPE_FIELD_DESC);
        oprot.writeString(struct.graphType);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UPlotOptionsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public UPlotOptionsTupleScheme getScheme() {
      return new UPlotOptionsTupleScheme();
    }
  }

  private static class UPlotOptionsTupleScheme extends org.apache.thrift.scheme.TupleScheme<UPlotOptions> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UPlotOptions struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetGraphType()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetGraphType()) {
        oprot.writeString(struct.graphType);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UPlotOptions struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.graphType = iprot.readString();
        struct.setGraphTypeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

